#!/bin/bash -l
###BSUB -W 4:00
#BSUB -W 24:00
#BSUB -J openai-vracer-irl
#BSUB -o openai-vracer-irl-%J.out
#BSUB -e openai-vracer-irl-%J.err
#BSUB -n 12
#BSUB -N wadaniel@ethz.ch
#bsub -R "rusage[mem=8192]"

source /cluster/apps/local/env2lmod.sh
module purge
module load gcc/8.2.0 python/3.9.9 openmpi/4.0.2 gsl/2.6
module load git-lfs

cd ..
export OMP_NUM_THREADS=12
source settings_irl.sh

BASE="${SCRATCH}/openAI_marl_march/${RUN}"
DIR="${BASE}/_result_irl_${ENV}_${RUN}/"

mkdir ${DIR} -p
touch "${DIR}/run.config"
echo ENV    ${ENV} >> "${DIR}/run.config"
echo EBRU   ${EBRU} >> "${DIR}/run.config"
echo DBS    ${DBS} >> "${DIR}/run.config"
echo BBS    ${BBS} >> "${DIR}/run.config"
echo BSS    ${BSS} >> "${DIR}/run.config"
echo EXP    ${EXP} >> "${DIR}/run.config"
echo RNN    ${RNN} >> "${DIR}/run.config"
echo POL    ${POL} >> "${DIR}/run.config"
echo DAT    ${DAT} >> "${DIR}/run.config"
echo RUN    ${RUN} >> "${DIR}/run.config"

cp -r run-vracer-irl.py ${BASE}
cp -r settings_irl.sh ${BASE}
cp -r _model ${BASE}
cp observations*${ENV}* ${BASE}

pushd .
cd ${BASE}

python3 run-vracer-irl.py --env ${ENV} --ebru ${EBRU} --dbs ${DBS} --bbs ${BBS} --bss ${BSS} --exp ${EXP} --rnn ${RNN} --pol ${POL} --dat ${DAT} --run ${RUN}

popd

python3 -m korali.plot --dir $DIR --out "${ENV}_${RUN}.png"
python3 -m korali.rlview --dir $DIR --out "irl-${ENV}_${RUN}.png" --showObservations --showCI 0.8
python3 -m korali.rlview --dir $DIR --out "firl-${ENV}_${RUN}.png" --featureReward --showObservations --showCI 0.8

date 

code=$?

exit $code
